// Copyright 2018 Twitter, Inc.
// Licensed under the Apache License, Version 2.0
// http://www.apache.org/licenses/LICENSE-2.0

const fs = require('fs-extra');
const { readdirSync, readFileSync, writeFileSync } = require('fs');
const path = require('path');
const prettier = require('prettier');
const process = require('process');
/*
import fs from 'fs-extra'
import { readdirSync, readFileSync, writeFileSync } from 'fs'
import path from 'path'
import prettier from 'prettier'
import process from 'process'
 */

const appRoot = `${process.cwd()}`;
const srcDir = `${appRoot}/config/`;
const destDir = path.join(appRoot, 'src');

const DEFAULT_CONFIG = 'version3';
const COMMENT = '// This file is generated by scripts/buildConfig.js \n';

const getVersion = (fileName) => fileName.split('.json')[0].replace('v', 'version');

const configs = {};
readdirSync(srcDir).forEach((file) => {
  if (file.indexOf('json') > -1) {
    const config = JSON.parse(readFileSync(path.join(srcDir, file)));
    const version = getVersion(file);
    configs[version] = config;
  }
});

configs.defaults = Object.assign({}, configs[DEFAULT_CONFIG]);

const code = `${COMMENT} export default ${JSON.stringify(configs)}`;
const destFile = path.join(destDir, 'configs.js');
console.log({ destFile });

fs.removeSync(destFile);

writeFileSync(destFile, JSON.stringify(prettier.format(code)));
